<a href="https://colab.research.google.com/github/Ali-Iftikhar/hello-world/blob/master/challenge1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
xxx = np.random.randint(low=1, high=10, size=10)
print(xxx)

[7 1 5 8 8 3 5 5 9 1]


In [4]:
xx = np.random.choice(10, 10, replace=False)
print(xx)

[4 3 7 0 8 6 9 2 1 5]


In [6]:
x = np.array([4, 3, 7, 10, 8, 6, 9, 2, 1, 5])
print(x)

[ 4  3  7 10  8  6  9  2  1  5]


In [12]:
pay = np.zeros(len(x))
print(pay)
for i in range(len(x)):
  if i == 0:
    pay[i] = x[i]
  else: 
    pay[i] = abs(x[i] - x[i-1])

print(pay)

mean10 = np.mean(pay)
print(mean10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 1. 4. 3. 2. 2. 3. 7. 1. 4.]
3.1


In [17]:
yyy = np.random.choice(20, 20, replace=False)
print(yyy)

[18  1  2  8  4  9  3 10  6  5  7 19 17  0 14 11 15 12 13 16]


In [18]:
y = np.array([18,  1,  2,  8,  4,  9,  3, 10,  6,  5,  7, 19, 17,  20, 14, 11, 15, 12, 13, 16])
print(y)

[18  1  2  8  4  9  3 10  6  5  7 19 17 20 14 11 15 12 13 16]


In [19]:
pay20 = np.zeros(len(y))
print(pay20)
for i in range(len(y)):
  if i == 0:
    pay20[i] = y[i]
  else: 
    pay20[i] = abs(y[i] - y[i-1])

print(pay20)

mean20 = np.mean(pay20)
print(mean20)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[18. 17.  1.  6.  4.  5.  6.  7.  4.  1.  2. 12.  2.  3.  6.  3.  4.  3.
  1.  3.]
5.4


In [21]:
std20 = np.std(pay20)
print(std20)

4.747630988187687


In [22]:
std10 = np.std(pay)
print(std10)

1.7
